sudo: required

services:
  - docker

before_install:
  - docker build -t travistest .

script:
  - docker run travistest id
  - docker run travistest uname -a
  - docker run travistest ps aux
  - docker run travistest lsb_release -a
