language: bash
sudo: required

services:
- docker

before_install:
- docker build -t travistest .

env:
- SUITE="zsteg" OPTS="-s -f -v"

script:
- docker run -e VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh -e SUITE=$SUITE -e OPTS=$OPTS --rm travistest /bin/bash bash -c "echo $OPTS $SUITE"

